### ISSUE TITLE
Foot Units

### ISSUE THREAD

**Issue by caseymtimm** [hanskellner/Fusion360ImportCSVPoints#1]
The conversion from feet to centimeters is off. It is 25.4, but should be 30.48. I attached a diff of the fix.

[diff.txt](https://github.com/hanskellner/Fusion360ImportCSVPoints/files/3442478/diff.txt)

**Comment by hanskellner** [comment]
@caseymtimm Duh!  Will submit the fix now.  Thanks for pointing it out.
