### ISSUE TITLE
Is this still working with latest version on 18-jun-2020 ?

### ISSUE THREAD

**Issue by pkarpi** [hanskellner/Fusion360ImportCSVPoints#2]
Asking, because I have installed it in %appdata%\Autodesk\Autodesk Fusion 360\API\Scripts, but can't see it in scripts to run.

**Comment by hanskellner** [comment]
Hi @pekezu - Let me give it a test and verify.  Also, have you used the "+" button to add the script?  Thanks.

**Comment by hanskellner** [comment]
@pekezu I've verified that it's working with the current version although large CSV point files do take a long time to load.  Investigating that.

Be sure you have added the script by using the "+" button to display the file dialog, selecting the folder containing the script, and clicking Open.  It should then appear in the list of scripts.

**Comment by Bartlettracing** [comment]
Is it possible to modify the script so when it brings them in it will draw straight lines between the points?

**Comment by pkarpi** [comment]
Thanks, Hans!

to 18. kesäk. 2020 klo 19.00 Hans <notifications@github.com> kirjoitti:

**Comment by hanskellner** [comment]
@Bartlettracing yes, that would be very easy to change.  But, the support is *already* in there ;)  When you run it, just select the "Style" dropdown and pick Line.
